version: '3'
services:
  flask-app:
    build:
      context: ./emotionAnalysisFromText/
    ports:
      - "5000:5000"
    networks:
      - app-network

  java-app:
    build:
      context: ./DearDiary  # Java uygulamasının bulunduğu dizin
      dockerfile: Dockerfile  # Java uygulaması için Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask-app
      - postgres  # PostgreSQL servisi de buraya dahil edilmeli
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/postgres  # PostgreSQL bağlantısı
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
