version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dear-diary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dear-diary-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 123456

volumes:
  postgres-data:
