  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            if ! [ -x "$(command -v docker)" ]; then
              echo "Docker not found, installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo usermod -aG docker $USER
            fi

            docker stop myapp-container || true
            docker rm myapp-container || true
            docker stop emotion-api-container || true
            docker rm emotion-api-container || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/emotion-api:latest

            docker network ls | grep app-network || docker network create app-network

            docker run -d --name emotion-api-container --network app-network -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/emotion-api:latest

            docker run -d --name myapp-container --network app-network -p 8080:8080 \
              -e DB_URL=jdbc:postgresql://postgres-db:5432/postgres \
              -e DB_USERNAME=postgres \
              -e DB_PASSWORD=123456 \
              ${{ secrets.DOCKER_USERNAME }}/myapp:latest